version: '3.8'

services:
  vue-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-vue-app:latest
    container_name: vue-docker-app
    ports:
      - "5173:80"    # 将本地5173端口映射到容器80端口，可根据需要修改
    restart: unless-stopped